//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBDepotEntities : DbContext
    {
        public DBDepotEntities()
            : base("name=DBDepotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_DamagedDrug> tb_DamagedDrug { get; set; }
        public virtual DbSet<tb_DepotDrug> tb_DepotDrug { get; set; }
        public virtual DbSet<tb_DepotIn> tb_DepotIn { get; set; }
        public virtual DbSet<tb_DepotInfo> tb_DepotInfo { get; set; }
        public virtual DbSet<tb_DepotOut> tb_DepotOut { get; set; }
        public virtual DbSet<tb_DrugInfo> tb_DrugInfo { get; set; }
        public virtual DbSet<tb_SupplierInfo> tb_SupplierInfo { get; set; }
        public virtual DbSet<tb_Warning> tb_Warning { get; set; }
        public virtual DbSet<tb_Purchase> tb_Purchase { get; set; }
        public virtual DbSet<tb_PurchaseDrugs> tb_PurchaseDrugs { get; set; }
        public virtual DbSet<StockView> StockViews { get; set; }
        public virtual DbSet<drugCheck> drugChecks { get; set; }
    }
}
