//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drugCheck
    {
        public int depotId { get; set; }
        public int drugId { get; set; }
        public string drugName { get; set; }
        public string depotName { get; set; }
        public Nullable<System.DateTime> lateDate { get; set; }
        public Nullable<System.DateTime> earlyDate { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> batchs { get; set; }
    }
}
