//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DepotDrug
    {
        public tb_DepotDrug()
        {
            this.tb_DamagedDrug = new HashSet<tb_DamagedDrug>();
            this.tb_Warning = new HashSet<tb_Warning>();
            this.tb_DepotOut = new HashSet<tb_DepotOut>();
        }
    
        public int Id { get; set; }
        public int DepotId { get; set; }
        public int DrugId { get; set; }
        public int Num { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int DepotInId { get; set; }
    
        public virtual ICollection<tb_DamagedDrug> tb_DamagedDrug { get; set; }
        public virtual tb_DepotInfo tb_DepotInfo { get; set; }
        public virtual tb_DrugInfo tb_DrugInfo { get; set; }
        public virtual ICollection<tb_Warning> tb_Warning { get; set; }
        public virtual tb_DepotIn tb_DepotIn { get; set; }
        public virtual ICollection<tb_DepotOut> tb_DepotOut { get; set; }
    }
}
