//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Warning
    {
        public int Id { get; set; }
        public int DepotDrugId { get; set; }
        public System.DateTime WarningDays { get; set; }
    
        public virtual tb_DepotDrug tb_DepotDrug { get; set; }
    }
}
